package com.lyhn.coreworkflowjava.workflow.engine.domain;
import com.lyhn.coreworkflowjava.workflow.engine.constants.NodeExecStatusEnum;
import com.lyhn.coreworkflowjava.workflow.engine.domain.callbacks.GenerateUsage;
import com.lyhn.coreworkflowjava.workflow.exception.NodeCustomException;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;

@Data
public class NodeRunResult {
    /**
     * Input data passed to the node.
     */
    private Map<String, Object> inputs = new HashMap<>(); // 节点执行时的输入参数

    /**
     * Output data produced by the node.
     */
    private Map<String, Object> outputs = new HashMap<>(); // 节点执行时的输出结果

    /**
     * Error outputs produced by the node.
     */
    private Map<String, Object> errorOutputs = new HashMap<>();

    /**
     * Raw output from the node execution.
     */
    private String rawOutput = "";

    /**
     * Answer content generated by the node.
     */
    private String nodeAnswerContent = "";

    /**
     * Reasoning content generated by the node.
     */
    private String nodeAnswerReasoningContent = "";

    /**
     * Token cost information for the node execution.
     */
    private GenerateUsage tokenCost = new GenerateUsage();

    /**
     * Error information if the node execution failed.
     */
    private NodeCustomException error = null;

    /**
     * Status of the node execution.
     */
    private NodeExecStatusEnum status;
}